name: Bearer Scan

on: [push]

jobs:
    bearer-scan:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Report
          id: report
          uses: bearer/bearer-action@v2
          with:
            path: .
            format: html
          continue-on-error: true
        - name: Upload Report
          uses: actions/upload-artifact@v3
          with:
            name: bearer-scan
            path: /workspaces/unisa-guardian-store/bearer-scan.html

          
