name: Bearer Scan

on: [push]

jobs:
    bearer-scan:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Report
          id: report
          uses: bearer/bearer-action@v2
